# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource Newspaper`

attributes:
  type:
    type: string
    multiple: true
    index_keys:
      - "type_sim"
      - "type_tesim"    
    form:
      required: false
      primary: false
      multiple: true
  date:
    type: date_time
    multiple: true
    index_keys:
      - "date_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  searchable_date:
    type: string
    multiple: false
    index_keys:
      - "searchable_date_sim"
      - "searchable_date_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  date_modified:
    type: date_time
    multiple: true
    form:
      primary: false
    index_keys:
      - "date_modified_sim"
      - "date_modified_tesim"
  volume:
    type: string
    multiple: false
    index_keys:
      - "volume_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  issue:
    type: string
    multiple: false
    index_keys:
      - "issue_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  format:
    type: string
    multiple: false
    index_keys:
      - "format_sim"
      - "format_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  repository:
    type: string
    multiple: false
    index_keys:
      - "repository_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  repository_collection:
    type: string
    multiple: false
    index_keys:
      - "repository_collection_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  local_rights_statement:
    type: string
    multiple: false
    index_keys:
      - "local_rights_statement_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  standardized_rights_statement:
    type: string
    multiple: false
    index_keys:
      - "local_rights_statement_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  digital_collection:
    type: string
    multiple: false
    index_keys:
      - "digital_collection_sim"
      - "digital_collection_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  digital_publisher:
    type: string
    multiple: false
    index_keys:
      - "digital_publisher_sim"
      - "digital_publisher_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  digital_specifications:
    type: string
    multiple: false
    index_keys:
      - "digital_specifications_sim"
      - "digital_specifications_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  contact:
    type: string
    multiple: false
    index_keys:
      - "contact_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  ada_note:
    type: string
    multiple: false
    index_keys:
      - "ada_note_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  feedback_form:
    type: string
    multiple: false
    index_keys:
      - "feedback_form_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  oclc_number:
    type: string
    multiple: false
    index_keys:
      - "oclc_number_tesim"    
    form:
      required: false
      primary: false
      multiple: false
  contentdm_number:
    type: string
    multiple: false
    index_keys:
      - "contentdm_number_tesim"    
    form:
      required: false
      primary: false
      multiple: false
